<?xml version="1.0" encoding="UTF-8"?><testrun name="CourseRepositoryTest" project="JPA_Spring_Hibernate" tests="3" started="3" failures="0" errors="3" ignored="0">
  <testsuite name="com.jpa.repository.CourseRepositoryTest" time="12.086" displayname="CourseRepositoryTest" uniqueid="[engine:junit-vintage]/[runner:com.jpa.repository.CourseRepositoryTest]">
    <testcase name="deleteById_basic" classname="com.jpa.repository.CourseRepositoryTest" time="0.002" displayname="deleteById_basic" uniqueid="[engine:junit-vintage]/[runner:com.jpa.repository.CourseRepositoryTest]/[test:deleteById_basic(com.jpa.repository.CourseRepositoryTest)]">
      <error>java.lang.IllegalStateException: Failed to load ApplicationContext&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)&#13;
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)&#13;
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)&#13;
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)&#13;
	at java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)&#13;
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)&#13;
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)&#13;
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)&#13;
	... 45 more&#13;
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)&#13;
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)&#13;
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)&#13;
	at com.jpa.repository.CourseRepository$$EnhancerBySpringCGLIB$$1aab7058.deleteById(&lt;generated&gt;)&#13;
	at com.jpa.JpaSpringHibernateApplication.run(JpaSpringHibernateApplication.java:29)&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)&#13;
	... 50 more&#13;
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:250)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:258)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)&#13;
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)&#13;
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:184)&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)&#13;
	... 60 more&#13;
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)&#13;
	at org.h2.message.DbException.get(DbException.java:194)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)&#13;
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)&#13;
	at org.h2.engine.Database.getPageStore(Database.java:2659)&#13;
	at org.h2.engine.Database.open(Database.java:675)&#13;
	at org.h2.engine.Database.openDatabase(Database.java:307)&#13;
	at org.h2.engine.Database.&lt;init&gt;(Database.java:301)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:74)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:192)&#13;
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:166)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:29)&#13;
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:173)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:152)&#13;
	at org.h2.Driver.connect(Driver.java:69)&#13;
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)&#13;
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)&#13;
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)&#13;
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:115)&#13;
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)&#13;
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)&#13;
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)&#13;
	... 67 more&#13;
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/nlshikha/test.mv.db [1.4.200/7]&#13;
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)&#13;
	at org.h2.mvstore.FileStore.open(FileStore.java:172)&#13;
	at org.h2.mvstore.MVStore.&lt;init&gt;(MVStore.java:381)&#13;
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)&#13;
	... 91 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="findById_basic" classname="com.jpa.repository.CourseRepositoryTest" time="0.001" displayname="findById_basic" uniqueid="[engine:junit-vintage]/[runner:com.jpa.repository.CourseRepositoryTest]/[test:findById_basic(com.jpa.repository.CourseRepositoryTest)]">
      <error>java.lang.IllegalStateException: Failed to load ApplicationContext&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)&#13;
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)&#13;
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)&#13;
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)&#13;
	at java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)&#13;
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)&#13;
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)&#13;
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)&#13;
	... 45 more&#13;
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)&#13;
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)&#13;
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)&#13;
	at com.jpa.repository.CourseRepository$$EnhancerBySpringCGLIB$$1aab7058.deleteById(&lt;generated&gt;)&#13;
	at com.jpa.JpaSpringHibernateApplication.run(JpaSpringHibernateApplication.java:29)&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)&#13;
	... 50 more&#13;
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:250)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:258)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)&#13;
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)&#13;
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:184)&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)&#13;
	... 60 more&#13;
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)&#13;
	at org.h2.message.DbException.get(DbException.java:194)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)&#13;
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)&#13;
	at org.h2.engine.Database.getPageStore(Database.java:2659)&#13;
	at org.h2.engine.Database.open(Database.java:675)&#13;
	at org.h2.engine.Database.openDatabase(Database.java:307)&#13;
	at org.h2.engine.Database.&lt;init&gt;(Database.java:301)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:74)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:192)&#13;
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:166)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:29)&#13;
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:173)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:152)&#13;
	at org.h2.Driver.connect(Driver.java:69)&#13;
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)&#13;
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)&#13;
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)&#13;
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:115)&#13;
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)&#13;
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)&#13;
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)&#13;
	... 67 more&#13;
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/nlshikha/test.mv.db [1.4.200/7]&#13;
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)&#13;
	at org.h2.mvstore.FileStore.open(FileStore.java:172)&#13;
	at org.h2.mvstore.MVStore.&lt;init&gt;(MVStore.java:381)&#13;
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)&#13;
	... 91 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="save_basic" classname="com.jpa.repository.CourseRepositoryTest" time="0.0" displayname="save_basic" uniqueid="[engine:junit-vintage]/[runner:com.jpa.repository.CourseRepositoryTest]/[test:save_basic(com.jpa.repository.CourseRepositoryTest)]">
      <error>java.lang.IllegalStateException: Failed to load ApplicationContext&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)&#13;
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)&#13;
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)&#13;
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)&#13;
	at java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)&#13;
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)&#13;
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)&#13;
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)&#13;
	... 45 more&#13;
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)&#13;
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)&#13;
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)&#13;
	at com.jpa.repository.CourseRepository$$EnhancerBySpringCGLIB$$1aab7058.deleteById(&lt;generated&gt;)&#13;
	at com.jpa.JpaSpringHibernateApplication.run(JpaSpringHibernateApplication.java:29)&#13;
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)&#13;
	... 50 more&#13;
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&#13;
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:250)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:258)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)&#13;
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)&#13;
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:184)&#13;
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)&#13;
	... 60 more&#13;
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)&#13;
	at org.h2.message.DbException.get(DbException.java:194)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)&#13;
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)&#13;
	at org.h2.engine.Database.getPageStore(Database.java:2659)&#13;
	at org.h2.engine.Database.open(Database.java:675)&#13;
	at org.h2.engine.Database.openDatabase(Database.java:307)&#13;
	at org.h2.engine.Database.&lt;init&gt;(Database.java:301)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:74)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:192)&#13;
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:166)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:29)&#13;
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:173)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:152)&#13;
	at org.h2.Driver.connect(Driver.java:69)&#13;
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)&#13;
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)&#13;
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)&#13;
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:115)&#13;
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)&#13;
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)&#13;
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)&#13;
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)&#13;
	... 67 more&#13;
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/nlshikha/test.mv.db [1.4.200/7]&#13;
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)&#13;
	at org.h2.mvstore.FileStore.open(FileStore.java:172)&#13;
	at org.h2.mvstore.MVStore.&lt;init&gt;(MVStore.java:381)&#13;
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)&#13;
	... 91 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
